version: '3'
services:
  cosmos:
    image: buildkite/puppeteer:v3.0.4
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules/
    entrypoint: /bin/sh -c
    command:
      - yarn --frozen-lockfile && yarn cosmos
  regression:
    image: buildkite/puppeteer:v3.0.4
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    entrypoint: /bin/sh -c
    command:
      - npx wait-on http://cosmos:5000 && COSMOS_HOSTNAME=cosmos yarn test:visual
    depends_on:
      - cosmos

volumes:
  node_modules:
